// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/kenji-kk/go-auth-template/internal/applicationService"
	"github.com/kenji-kk/go-auth-template/internal/handler"
	"github.com/kenji-kk/go-auth-template/internal/infra"
	"github.com/kenji-kk/go-auth-template/internal/repository"
)

// Injectors from wire.go:

func InitializeRootHandlers() handler.RootHandlers {
	db := infra.NewMysql()
	userRepository := repository.NewUserRepository(db)
	userApplicationService := applicationService.NewUserApplicationService(userRepository)
	userHandler := handler.NewUserHandler(userApplicationService)
	rootHandlers := handler.NewRootHandlers(userHandler)
	return rootHandlers
}
